import {
  Pencil,
  Trash3,
  CheckLg,
  XLg,
  Magic,
  Shuffle,
  PencilSquare,
} from "react-bootstrap-icons";

import Button from "../common/Button";
import Input from "../common/Input";
import AutoAdjustingInput from "../common/AutoAdjustingInput";
import Badge from "../common/Badge";

const GENERATION_METHODS = {
  ai: {
    label: "Generated by AI",
    icon: Magic,
    variant: "primary",
  },
  custom: {
    label: "Custom Choices",
    icon: PencilSquare,
    variant: "info",
  },
  random: {
    label: "Randomly Generated",
    icon: Shuffle,
    variant: "success",
  },
};

const DEFAULT_CHOICES = ["", "", "", ""];

const QuizPreviewItem = ({
  item,
  index,
  isEditing,
  editBuffer,
  onStartEdit,
  onCancelEdit,
  onSaveEdit,
  onDelete,
  onEditBufferChange,
}) => {
  const methodInfo =
    GENERATION_METHODS[item.generationMethod] || GENERATION_METHODS.random;

  const choices = item.choices || DEFAULT_CHOICES;

  const updateEditBuffer = (updates) => {
    onEditBufferChange({
      ...editBuffer,
      ...updates,
    });
  };

  const handleChoiceChange = (choiceIndex, value) => {
    const newChoices = [...(editBuffer.choices || DEFAULT_CHOICES)];

    newChoices[choiceIndex] = value;

    updateEditBuffer({
      choices: newChoices,
    });
  };

  return (
    <article
      className={`rounded-xl border p-5 transition-all duration-200 ${
        isEditing
          ? "border-primary bg-primary-light/10 shadow-sm"
          : "border-border bg-surface-hover hover:border-border-hover"
      }`}
    >
      <header className="mb-4 flex items-center justify-between gap-3 border-b border-border/60 pb-3">
        <div className="flex items-center gap-3">
          <span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary-light text-xs font-bold text-primary">
            {index + 1}
          </span>

          <Badge icon={methodInfo.icon} variant={methodInfo.variant}>
            {methodInfo.label}
          </Badge>
        </div>

        <div className="flex items-center gap-2">
          {isEditing ? (
            <>
              <Button
                type="button"
                variant="secondary"
                fit
                onClick={onCancelEdit}
              >
                <XLg size={12} />
                Cancel
              </Button>

              <Button type="button" fit onClick={onSaveEdit}>
                <CheckLg size={14} />
                Save
              </Button>
            </>
          ) : (
            <>
              <Button
                type="button"
                variant="secondary"
                fit
                onClick={onStartEdit}
              >
                <Pencil size={13} />
                Edit
              </Button>

              <Button
                type="button"
                variant="danger"
                fit
                onClick={onDelete}
                disabled={false}
                title="Delete question"
              >
                <Trash3 size={14} />
              </Button>
            </>
          )}
        </div>
      </header>

      {isEditing && editBuffer ? (
        <div className="flex flex-col gap-4 animate-in fade-in duration-200">
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-5">
            <div className="lg:col-span-3">
              <AutoAdjustingInput
                id={`edit-question-${index}`}
                name="question"
                label="Question Prompt"
                value={editBuffer.question}
                onChange={(event) =>
                  updateEditBuffer({
                    question: event.target.value,
                  })
                }
              />
            </div>

            <div className="lg:col-span-2">
              <AutoAdjustingInput
                id={`edit-answer-${index}`}
                name="answer"
                label="Correct Answer"
                value={editBuffer.answer}
                onChange={(event) =>
                  updateEditBuffer({
                    answer: event.target.value,
                  })
                }
              />
            </div>
          </div>

          <div className="rounded-xl border border-primary/20 bg-surface p-4">
            <span className="mb-3 block text-xs font-semibold uppercase tracking-wider text-primary">
              Multiple-Choice Options
            </span>

            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              {(editBuffer.choices || DEFAULT_CHOICES).map(
                (choice, choiceIndex) => (
                  <Input
                    key={choiceIndex}
                    id={`edit-choice-${index}-${choiceIndex}`}
                    label={`Option ${String.fromCharCode(65 + choiceIndex)}`}
                    value={choice}
                    onChange={(event) =>
                      handleChoiceChange(choiceIndex, event.target.value)
                    }
                  />
                ),
              )}
            </div>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-3">
          <div>
            <span className="text-xs font-semibold uppercase tracking-wider text-muted">
              Question
            </span>

            <p className="mt-1 text-base font-semibold text-foreground">
              {item.question || (
                <span className="italic text-muted">No prompt provided</span>
              )}
            </p>
          </div>

          <Badge variant="success" shape="rounded">
            <span>Correct Answer:</span>
            <span>{item.answer || "N/A"}</span>
          </Badge>

          {choices.some((choice) => choice) && (
            <div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-2">
              {choices.map((choice, choiceIndex) => {
                const optionLabel = String.fromCharCode(65 + choiceIndex);

                const isCorrect =
                  choice &&
                  item.answer &&
                  choice.trim().toLowerCase() ===
                    item.answer.trim().toLowerCase();

                return (
                  <div
                    key={choiceIndex}
                    className={`flex items-center gap-2.5 rounded-lg border p-2.5 text-xs transition-all ${
                      isCorrect
                        ? "border-success/40 bg-success/10 font-bold text-foreground"
                        : "border-border/70 bg-background/60 text-muted"
                    }`}
                  >
                    <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded bg-surface font-bold text-foreground">
                      {optionLabel}
                    </span>

                    <span className="truncate">
                      {choice || <span className="italic">Empty Option</span>}
                    </span>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}
    </article>
  );
};

export default QuizPreviewItem;
